### ISSUE TITLE
Demo loads unsecure resources

### ISSUE THREAD

**Issue by FoxxMD** [peterolson/jqCube#2]
The [demo](https://peterolson.github.io/jqCube/demo/demo.html) redirects to https but then attempts to load unsecure resources resulting in this

![screen shot 2017-04-28 at 9 54 31 am](https://cloud.githubusercontent.com/assets/4663766/25531735/bce11eea-2bf8-11e7-97d0-f15f9eccab5a.png)

Unsecure resources that were blocked (by Chrome 57)

* http://code.jquery.com/jquery-1.11.0.min.js
* http://www.play.vg/games/4-Asteroids.html

Additionally these images raised a warning because they were unsecure:

* http://dl.dropbox.com/u/25059665/wait.gif
* http://dl.dropbox.com/u/25059665/CoolGear%252020.png

**Comment by peterolson** [comment]
Thanks, I've fixed the issue
